In [23]:
import pandas as pd
import numpy as np
import  matplotlib.pyplot as plt
import seaborn as sns
import warnings
%matplotlib inline
warnings.filterwarnings('ignore')

In [39]:
df=pd.read_excel(r"C:\Users\Pc\Downloads\flight_price.xlsx")

In [40]:
df

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [41]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [42]:
df.sample(2)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
6962,Jet Airways,24/03/2019,Kolkata,Banglore,CCU → BOM → BLR,19:45,20:40 25 Mar,24h 55m,1 stop,No info,13759
5689,Jet Airways,15/04/2019,Banglore,Delhi,BLR → DEL,07:10,10:10,3h,non-stop,No info,7229

In [43]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Date_of_Journey  10683 non-null  str
 2   Source           10683 non-null  str
 3   Destination      10683 non-null  str
 4   Route            10682 non-null  str
 5   Dep_Time         10683 non-null  str
 6   Arrival_Time     10683 non-null  str
 7   Duration         10683 non-null  str
 8   Total_Stops      10682 non-null  str
 9   Additional_Info  10683 non-null  str
 10  Price            10683 non-null  int64
dtypes: int64(1), str(10)
memory usage: 1.8 MB

In [44]:
df.describe()

              Price
count  10683.000000
mean    9087.064121
std     4611.359167
min     1759.000000
25%     5277.000000
50%     8372.000000
75%    12373.000000
max    79512.000000

In [47]:
df['Date_of_Journey']

0        24/03/2019
1         1/05/2019
2         9/06/2019
3        12/05/2019
4        01/03/2019
            ...
10678     9/04/2019
10679    27/04/2019
10680    27/04/2019
10681    01/03/2019
10682     9/05/2019
Name: Date_of_Journey, Length: 10683, dtype: str

In [50]:
df['Date'] = df['Date_of_Journey'].str.split('/').str[0]
df['month'] = df['Date_of_Journey'].str.split('/').str[1]
df['Year'] = df['Date_of_Journey'].str.split('/').str[2]

In [51]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Date_of_Journey  10683 non-null  str
 2   Source           10683 non-null  str
 3   Destination      10683 non-null  str
 4   Route            10682 non-null  str
 5   Dep_Time         10683 non-null  str
 6   Arrival_Time     10683 non-null  str
 7   Duration         10683 non-null  str
 8   Total_Stops      10682 non-null  str
 9   Additional_Info  10683 non-null  str
 10  Price            10683 non-null  int64
 11  Date             10683 non-null  object
 12  month            10683 non-null  object
 13  Year             10683 non-null  object
dtypes: int64(1), object(3), str(10)
memory usage: 2.0+ MB

In [53]:
df['Date'] =df['Date'].astype(int)
df['month'] = df['month'].astype(int)
df['Year']= df['Year'].astype(int)

In [54]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Date_of_Journey  10683 non-null  str
 2   Source           10683 non-null  str
 3   Destination      10683 non-null  str
 4   Route            10682 non-null  str
 5   Dep_Time         10683 non-null  str
 6   Arrival_Time     10683 non-null  str
 7   Duration         10683 non-null  str
 8   Total_Stops      10682 non-null  str
 9   Additional_Info  10683 non-null  str
 10  Price            10683 non-null  int64
 11  Date             10683 non-null  int64
 12  month            10683 non-null  int64
 13  Year             10683 non-null  int64
dtypes: int64(4), str(10)
memory usage: 2.0 MB

In [55]:
df.drop('Date_of_Journey',axis=1,inplace=True)

In [56]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Source           10683 non-null  str
 2   Destination      10683 non-null  str
 3   Route            10682 non-null  str
 4   Dep_Time         10683 non-null  str
 5   Arrival_Time     10683 non-null  str
 6   Duration         10683 non-null  str
 7   Total_Stops      10682 non-null  str
 8   Additional_Info  10683 non-null  str
 9   Price            10683 non-null  int64
 10  Date             10683 non-null  int64
 11  month            10683 non-null  int64
 12  Year             10683 non-null  int64
dtypes: int64(4), str(9)
memory usage: 1.9 MB

In [59]:
df['Arrival_Time'].apply(lambda x:x.split(' ')[0])

0        01:10
1        13:15
2        04:25
3        23:30
4        21:35
         ...
10678    22:25
10679    23:20
10680    11:20
10681    14:10
10682    19:15
Name: Arrival_Time, Length: 10683, dtype: str

In [67]:
df['Arrival_hour']=df['Arrival_Time'].str.split(' :').str[0]
df['Arrival_min']=df['Arrival_Time'].str.split(' :').str[1]

In [71]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Source           10683 non-null  str
 2   Destination      10683 non-null  str
 3   Route            10682 non-null  str
 4   Dep_Time         10683 non-null  str
 5   Arrival_Time     10683 non-null  datetime64[us]
 6   Duration         10683 non-null  str
 7   Total_Stops      10682 non-null  str
 8   Additional_Info  10683 non-null  str
 9   Price            10683 non-null  int64
 10  Date             10683 non-null  int64
 11  month            10683 non-null  int64
 12  Year             10683 non-null  int64
 13  Arrival_min      10683 non-null  int32
 14  Arrival_hour     10683 non-null  int32
dtypes: datetime64[us](1), int32(2), int64(4), str(8)
memory usage: 1.9 MB

In [70]:
df['Arrival_Time'] = pd.to_datetime(df['Arrival_Time'], errors='coerce')
df['Arrival_hour'] = df['Arrival_Time'].dt.hour
df['Arrival_min'] = df['Arrival_Time'].dt.minute

In [72]:
df.drop('Arrival_Time', axis=1, inplace=True)

In [74]:
df.sample(1)

,Airline,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Additional_Info,Price,Date,month,Year,Arrival_min,Arrival_hour
6238,IndiGo,Mumbai,Hyderabad,BOM → HYD,20:05,1h 35m,non-stop,No info,2227,27,6,2019,0,0

In [79]:
df['Dep_hour']=df['Dep_Time'].str.split(':').str[0]
df['Dep_min']=df['Dep_Time'].str.split(':').str[1]

In [83]:
df['Dep_hour']=df['Dep_hour'].astype(int)
df['Dep_min']=df['Dep_min'].astype(int)

In [84]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Source           10683 non-null  str
 2   Destination      10683 non-null  str
 3   Route            10682 non-null  str
 4   Dep_Time         10683 non-null  str
 5   Duration         10683 non-null  str
 6   Total_Stops      10682 non-null  str
 7   Additional_Info  10683 non-null  str
 8   Price            10683 non-null  int64
 9   Date             10683 non-null  int64
 10  month            10683 non-null  int64
 11  Year             10683 non-null  int64
 12  Arrival_min      10683 non-null  int32
 13  Arrival_hour     10683 non-null  int32
 14  Dep_hour         10683 non-null  int64
 15  Dep_min          10683 non-null  int64
dtypes: int32(2), int64(6), str(8)
memory usage: 1.9 MB

In [86]:
df.drop('Dep_Time',axis =1,inplace=True)

In [87]:
df

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,month,Year,Arrival_min,Arrival_hour,Dep_hour,Dep_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897,24,3,2019,0,0,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2 stops,No info,7662,1,5,2019,0,0,5,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2 stops,No info,13882,9,6,2019,0,0,9,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1 stop,No info,6218,12,5,2019,0,0,18,5
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1 stop,No info,13302,1,3,2019,0,0,16,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,2h 30m,non-stop,No info,4107,9,4,2019,0,0,19,55
10679,Air India,Kolkata,Banglore,CCU → BLR,2h 35m,non-stop,No info,4145,27,4,2019,0,0,20,45
10680,Jet Airways,Banglore,Delhi,BLR → DEL,3h,non-stop,No info,7229,27,4,2019,0,0,8,20
10681,Vistara,Banglore,New Delhi,BLR → DEL,2h 40m,non-stop,No info,12648,1,3,2019,0,0,11,30
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,8h 20m,2 stops,No info,11753,9,5,2019,0,0,10,55

In [88]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Source           10683 non-null  str
 2   Destination      10683 non-null  str
 3   Route            10682 non-null  str
 4   Duration         10683 non-null  str
 5   Total_Stops      10682 non-null  str
 6   Additional_Info  10683 non-null  str
 7   Price            10683 non-null  int64
 8   Date             10683 non-null  int64
 9   month            10683 non-null  int64
 10  Year             10683 non-null  int64
 11  Arrival_min      10683 non-null  int32
 12  Arrival_hour     10683 non-null  int32
 13  Dep_hour         10683 non-null  int64
 14  Dep_min          10683 non-null  int64
dtypes: int32(2), int64(6), str(7)
memory usage: 1.8 MB

In [89]:
df['Total_Stops'].unique()

<ArrowStringArray>
['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops']
Length: 6, dtype: str

In [90]:
df['Total_Stops'].isnull().sum()

np.int64(1)

In [91]:
df[df['Total_Stops'].isnull()]

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,month,Year,Arrival_min,Arrival_hour,Dep_hour,Dep_min
9039,Air India,Delhi,Cochin,NaN,23h 40m,NaN,No info,7480,6,5,2019,0,0,9,45

In [92]:
df['Total_Stops'].mode()

0    1 stop
Name: Total_Stops, dtype: str

In [96]:
df['Total_Stops']=df['Total_Stops'].map({'non-stop':0, '1 stop':1, '2 stops':2, '3 stops':3, '4 stops':4, np.nan:0})

In [97]:
df['Total_Stops'].isnull().sum()

np.int64(0)

In [98]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Source           10683 non-null  str
 2   Destination      10683 non-null  str
 3   Route            10682 non-null  str
 4   Duration         10683 non-null  str
 5   Total_Stops      10683 non-null  int64
 6   Additional_Info  10683 non-null  str
 7   Price            10683 non-null  int64
 8   Date             10683 non-null  int64
 9   month            10683 non-null  int64
 10  Year             10683 non-null  int64
 11  Arrival_min      10683 non-null  int32
 12  Arrival_hour     10683 non-null  int32
 13  Dep_hour         10683 non-null  int64
 14  Dep_min          10683 non-null  int64
dtypes: int32(2), int64(7), str(6)
memory usage: 1.7 MB

In [99]:
df

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,month,Year,Arrival_min,Arrival_hour,Dep_hour,Dep_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,0,No info,3897,24,3,2019,0,0,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2,No info,7662,1,5,2019,0,0,5,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2,No info,13882,9,6,2019,0,0,9,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1,No info,6218,12,5,2019,0,0,18,5
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1,No info,13302,1,3,2019,0,0,16,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,2h 30m,0,No info,4107,9,4,2019,0,0,19,55
10679,Air India,Kolkata,Banglore,CCU → BLR,2h 35m,0,No info,4145,27,4,2019,0,0,20,45
10680,Jet Airways,Banglore,Delhi,BLR → DEL,3h,0,No info,7229,27,4,2019,0,0,8,20
10681,Vistara,Banglore,New Delhi,BLR → DEL,2h 40m,0,No info,12648,1,3,2019,0,0,11,30
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,8h 20m,2,No info,11753,9,5,2019,0,0,10,55

In [100]:
df.drop('Route',axis=1,inplace=True)

In [101]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Source           10683 non-null  str
 2   Destination      10683 non-null  str
 3   Duration         10683 non-null  str
 4   Total_Stops      10683 non-null  int64
 5   Additional_Info  10683 non-null  str
 6   Price            10683 non-null  int64
 7   Date             10683 non-null  int64
 8   month            10683 non-null  int64
 9   Year             10683 non-null  int64
 10  Arrival_min      10683 non-null  int32
 11  Arrival_hour     10683 non-null  int32
 12  Dep_hour         10683 non-null  int64
 13  Dep_min          10683 non-null  int64
dtypes: int32(2), int64(7), str(5)
memory usage: 1.5 MB

In [103]:
df['Duration_hours'] = df['Duration'].str.split('').str[0].str.split('h').str[0]

In [104]:
df['Duration_hours']

0
1
2
3
4
        ..
10678
10679
10680
10681
10682
Name: Duration_hours, Length: 10683, dtype: object

In [105]:
df.columns

Index(['Airline', 'Source', 'Destination', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price', 'Date', 'month', 'Year', 'Arrival_min',
       'Arrival_hour', 'Dep_hour', 'Dep_min', 'Duration_hours'],
      dtype='str')

In [106]:
df.Airline.unique()

<ArrowStringArray>
[                           'IndiGo',                         'Air India',
                       'Jet Airways',                          'SpiceJet',
                 'Multiple carriers',                             'GoAir',
                           'Vistara',                          'Air Asia',
           'Vistara Premium economy',              'Jet Airways Business',
 'Multiple carriers Premium economy',                            'Trujet']
Length: 12, dtype: str

In [107]:
df.Source.unique()

<ArrowStringArray>
['Banglore', 'Kolkata', 'Delhi', 'Chennai', 'Mumbai']
Length: 5, dtype: str

In [109]:
from sklearn.preprocessing import OneHotEncoder

In [110]:
encoder =OneHotEncoder()

In [111]:
df.columns

Index(['Airline', 'Source', 'Destination', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price', 'Date', 'month', 'Year', 'Arrival_min',
       'Arrival_hour', 'Dep_hour', 'Dep_min', 'Duration_hours'],
      dtype='str')

In [112]:
encoder.fit_transform(df[['Airline','Source','Destination']]).toarray()

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 0.]], shape=(10683, 23))